version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version 
      - docker login -u avinashgiragani -p avinash*1992
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 229392245290.dkr.ecr.us-east-1.amazonaws.com
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 229392245290.dkr.ecr.us-east-1.amazonaws.com/pythonflask:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 229392245290.dkr.ecr.us-east-1.amazonaws.com/pythonflask:latest
      - echo Writing image definitions file...
      - printf '[{"name":"py-container","imageUri":"%s"}]' 229392245290.dkr.ecr.us-east-1.amazonaws.com/pythonflask:latest > imagedefinitions.json
      - cat imagedefinitions.json 
artifacts:
    files: imagedefinitions.json
